[tool.towncrier]
directory = "changelog.d"
filename = "CHANGELOG.md"
start_string = "<!-- towncrier release notes start -->\n"
underlines = ["", "", ""]
title_format = "## [{version}](https://github.com/keesey/keesey-comics.com/tree/v{version}) - {project_date}"
issue_format = "[#{issue}](https://github.com/keesey/keesey-comics.com/issues/{issue})"

[[tool.towncrier.type]]
name = "Added"

[[tool.towncrier.type]]
name = "Changed"

[[tool.towncrier.type]]
name = "Deprecated"

[[tool.towncrier.type]]
name = "Fixed"

[[tool.towncrier.type]]
name = "Removed"

[[tool.towncrier.type]]
name = "Security"
